#!/usr/bin/env python3
"""Build a throwaway league config from a mock draft room.

    uv run python scripts/mock_config.py < paste.txt
    pbpaste | uv run python scripts/mock_config.py          # macOS
    uv run python scripts/mock_config.py --teams "Avery,Sage,Quinn,Your Team"

Testing the bridge needs a league whose teams are the ones in the room. A mock's teams are
strangers with names you cannot know in advance, and typing twelve of them by hand while a
draft is running is exactly how a buyer ends up unresolved -- which is the one failure the
bridge refuses to write through.

So: paste what the draft-results panel shows, and this reads the buyers out of it and
writes a config with those teams. It borrows the real league's cached snapshot rather than
building another one, because the player pool is identical and rebuilding costs a minute
you do not have mid-mock.

The result is disposable. Do not draft your real league against it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ff_helper.draft.bridge import YOUR_TEAM, parse_paste  # noqa: E402
from ff_helper.offline import load_config  # noqa: E402

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

TEMPLATE = """# Generated by scripts/mock_config.py -- a throwaway league for testing the bridge
# against a mock draft. Not your real league; do not draft Bust A Move against this.

name: {name}
league_id: "{league_id}"
season: "2026"
num_teams: {num_teams}
draft_type: auction
auction_budget: {budget}

# Borrow the real league's player pool instead of spending a minute rebuilding an
# identical one. Only the league settings differ between them.
snapshot_league_key: "{snapshot_key}"

roster:
  QB: 1
  WR: 2
  RB: 2
  TE: 1
  W/R/T: 1
  K: 1
  DEF: 1
  BN: 6

scoring:
  pass_yds: 0.04
  pass_td: 4
  int: -1
  rush_yds: 0.1
  rush_td: 6
  rec: 0.5
  rec_yds: 0.1
  rec_td: 6
  fum_lost: -2

# Yahoo calls your own team "Your Team" in the draft room, so that is what the buyers
# read as and what my_team has to be for a mock.
my_team: "{my_team}"
teams:
{teams}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--teams", help="Comma-separated team names, instead of reading a pasted board."
    )
    parser.add_argument("--out", type=Path, default=DATA_DIR / "league-mock.yaml")
    parser.add_argument(
        "--snapshot",
        default="offline.l.107878",
        help="League key whose cached snapshot to borrow. Defaults to Bust A Move's.",
    )
    parser.add_argument("--budget", type=int, default=200)
    parser.add_argument(
        "--num-teams",
        type=int,
        help="Pad out to this many teams if the paste has not shown them all yet.",
    )
    args = parser.parse_args()

    if args.teams:
        names = [name.strip() for name in args.teams.split(",") if name.strip()]
    else:
        if sys.stdin.isatty():
            print("Paste the draft-results panel, then press Ctrl-D on a blank line:\n")
        text = sys.stdin.read()
        if not text.strip():
            print("Nothing on stdin. Paste the draft-results panel, or pass --teams.")
            return 1
        sales = parse_paste(text)
        if not sales:
            print(
                "Could not read any sales from that. Is it the draft-results panel?\n"
                "You can also pass --teams 'Name One,Name Two,...' instead."
            )
            return 1
        # Order of first appearance, so the list is stable if you regenerate mid-draft --
        # team keys are positional, and reordering would re-attribute money already
        # recorded.
        names = list(dict.fromkeys(sale.buyer for sale in sales if sale.buyer))
        print(f"Read {len(sales)} sales, {len(names)} distinct buyers.")

    # Yahoo never names your own team in the results panel; it says "Your Team".
    mine = next((name for name in names if name.strip().lower() == YOUR_TEAM), None)
    if mine is None:
        mine = "Your Team"
        names.append(mine)
        print("No 'Your Team' in the paste yet -- added it, since that is what Yahoo")
        print("calls you once you win something.")

    target = args.num_teams or len(names)
    for index in range(len(names), target):
        names.append(f"Placeholder {index + 1}")
    if target > len(set(names)):
        print("Warning: duplicate team names; the later one will never be matched.")

    body = "\n".join(f'  - "{name}"' for name in names)
    args.out.write_text(
        TEMPLATE.format(
            name="Mock Draft",
            league_id="mock",
            num_teams=len(names),
            budget=args.budget,
            snapshot_key=args.snapshot,
            my_team=mine,
            teams=body,
        ),
        encoding="utf-8",
    )

    try:
        config = load_config(args.out)
    except Exception as exc:  # noqa: BLE001 - the point is to fail here, not at startup
        print(f"\nWrote {args.out} but it does not load: {exc}")
        return 1

    print(f"\nWrote {args.out} -- {config.league.num_teams} teams, ${args.budget} budget")
    for team in config.teams:
        print(f"   {team.name}{'  <- you' if team.is_mine else ''}")
    print(f"\nNow run:\n   uv run ff-helper --offline {args.out} --port 8779")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
